version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currencybird
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data: